version: "3.0"
services:
  bark-subscribe:
    image: kyuuseiryuu/bark_subscribe
    container_name: bark_subscribe
    volumes:
      - ./:/app/database
    environment:
      DOMAIN:
      BARK_SERVER:
    ports:
      - 3000:3000